### ISSUE TITLE
histogram

### ISSUE THREAD

**Issue by lpatiny** [image-js/core#13]
Returns an histogram of the points present in the picture
Options:
* alpha (by default false), we don't return the array for the alpha channel
* nbSlots, by default the number of colors allowed in the channel

Returns an array (if nbChannel + alpha == 1) or an array of array

Should work with all the formats, also with mask images

**Comment by MariaTrujillo** [comment]
The histogram is calculated for each color channel (R, G, B). The number of bins or slots is the maximum level according to the number of bits used to represent data in a pixel position. Commonly 8 bits (256 levels) is used, but in the near future we are going to use 12 bits...

**Comment by lpatiny** [comment]
Implemented
