### ISSUE TITLE
IJS.load returns an array in the last version ?

### ISSUE THREAD

**Issue by lpatiny** [image-js/core#145]
```
var image=IJS.load(value).then(
            function(image) {
                image.level();
            }
        );
```
Fails because it returns an array. Is this normal ?

**Comment by targos** [comment]
It can return an array (Stack), but only for tif files with multiple images.
see https://github.com/image-js/core/blob/27007514120ef377cc28a628f4bc652b3a1ecee5/src/image/load.js#L74-L82

**Comment by lpatiny** [comment]
OK we should check this. I had the impression my tiff where single images and it returns an error. There is an example image on : http://script.epfl.ch/script/HD/Load/kyZoBjZHeK?filename=test%40patiny.com%2FDemo%2FTest%2Ftest.tif if you could have a look
