### ISSUE TITLE
Be able to extend the stack

### ISSUE THREAD

**Issue by lpatiny** [image-js/core#218]
I don't know if it is easy but it would be great if all the methods that are available for an image are also available for a stack.

The only difference is that each time it will return an array of values instead of an array. Ideally if the return is an object it will return a new stack.

So if you have a stack
let stack=IJS.Stack.load();
let grey=stack.grey(); // would return a stack of grey images

@targos I don't know how easy it is to do ...

**Comment by targos** [comment]
You should use stack.map

Example: `stack.map(img => img.grey ())`
