### ISSUE TITLE
Documentation links to original code does not work

### ISSUE THREAD

**Issue by lpatiny** [image-js/core#220]
I don't remember if this is a known bug

https://image-js.github.io/core/#shape

**Comment by targos** [comment]
I'm not sure yet what is the reason, but I see a few issues related to the migration of the tests:

The [common.js](https://github.com/image-js/core/blob/master/src/__tests__/common.js) file is not a test. it should replace https://github.com/image-js/core/blob/master/src/node_modules/test/common.js

There are still import paths that have a lot of `..` and this one of the things we are trying to avoid with the migration .

I'll take an example: [`src/image/utility/__tests__/color.js`](https://github.com/image-js/core/blob/master/src/image/utility/__tests__/color.js
)
This file is at the wrong place. It is testing the functions from [`src/util/color.js`](https://github.com/image-js/core/blob/master/src/util/color.js). Therefore it should be placed in `src/util/__tests__` and require the file with `import {css2array, getDistinctColors} from '../color';`

**Comment by lpatiny** [comment]
You can help me moving common.js because now it does not work anymore.
I guess it should be rewritten using require ???

**Comment by targos** [comment]
fixed
