### ISSUE TITLE
why this speed difference ?

### ISSUE THREAD

**Issue by lpatiny** [image-js/core#223]
https://github.com/image-js/core/blob/e6cb9aa14c584edd03dade57eade96a42768a5cb/benchmark/grey.js#L15-L20

The 'red' is 6 times slower than 'grey' while it is indeed different approaches but the 'red' algorithm seems easier to calculate. @targos Any idea why this difference in speed ?

**Comment by targos** [comment]
because you put the algorithm 'lightness' instead of 'red' ?

**Comment by lpatiny** [comment]
Yes seems the main reason indeed :(
