### ISSUE TITLE
Coverage not being executed propertly

### ISSUE THREAD

**Issue by lpatiny** [image-js/core#227]
Seems a little bit complex for me ... @targos you could try to find out what is wrong ?

https://github.com/image-js/core/blob/23fa58a7f4a81ceb3cbf1d5f8aff31acc67c2ff3/package.json#L50

**Comment by targos** [comment]
Fixed in https://github.com/image-js/core/commit/3b715eee4cd0a66bbc6a772fc1b968469b4e4641
It's interesting because now we also have coverage for the tests and it highlights some errors in there !

**Comment by lpatiny** [comment]
But is strange that it tells that some of the tests are not executed no ?
https://coveralls.io/builds/8066780/source?filename=src%2Fimage%2F__tests__%2Fbinary.js#L11

**Comment by targos** [comment]
it is correct. nesting `it()` is not allowed. You can only nest `describe()`

**Comment by lpatiny** [comment]
OK thanks. Seems an easy way to improve coverage !!!
