### ISSUE TITLE
uppercase / lowercase homogeneity in filenames

### ISSUE THREAD

**Issue by lpatiny** [image-js/core#232]
I would like that looking at the filename we now if we describe a class.

This means that it should be Image.js and Stack.js, ROI.js

Currently it is mixed

![image](https://cloud.githubusercontent.com/assets/1484241/19133747/77dcfcc6-8b1f-11e6-8398-841935afb380.png)

@targos, what do you think ?

**Comment by targos** [comment]
+1 but I prefer camelCase everywhere so: Roi, RoiLayer, etc.

**Comment by lpatiny** [comment]
Most of the name are now correct.
