### ISSUE TITLE
Rotate an image 0, 90, 180 and 270

### ISSUE THREAD

**Issue by lpatiny** [image-js/core#235]
Add a new method 'rotate' that can apply on images

This first method would just rotate by step of 90°

This would be a 'in-place' modification and would be a filter. Get inspired by:

https://github.com/image-js/core/blob/master/src/image/filter/invert.js

**Comment by targos** [comment]
It can only be in place for square images so I would prefer to always return a new image

**Comment by lpatiny** [comment]
You don't think that with this in place we could just change the this.width and this.height for 90 and 270 rotation ?

**Comment by targos** [comment]
huh ? You will always have to move the pixels in `this.data`.

**Comment by lpatiny** [comment]
The question was in-place or not in-place. Of course we need to move the data but because it is easy to come back to the original image I think it would be in-place.
I don't know our rules to define inplace or not inplace but for me it is more if we can easily go back to the original image.

**Comment by targos** [comment]
> we can easily go back to the original image

I don't understand what that means

**Comment by lpatiny** [comment]
After making a rotation of 90° we can make one of -90° and we get the original image. Same is true for invert of an image. We apply it twice and we get the original image.

**Comment by targos** [comment]
That's also true if we make a copy.  I don't like to have to change (in place) something else than the data.
