### ISSUE TITLE
ERROR INSTALLING

### ISSUE THREAD

**Issue by NervenCid** [image-js/core#242]
Hello 👍 i tried install the package but i got these errors:

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\DiegoCamilo\AppData\Roaming\npm\node_modules\image-js\node_modules\canvas
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:canvas@1.5.0 canvas@1.5.0 install: `node-gyp rebuild`
npm WARN install:canvas@1.5.0 Exit status 1
Thnak you

**Comment by lpatiny** [comment]
image-js requires Canvas in order to be able to run in node and to pass the test.

In order to install Canvas on windows please follow the instructions from:

https://github.com/Automattic/node-canvas/wiki/Installation---Windows
