### ISSUE TITLE
median and name

### ISSUE THREAD

**Issue by lpatiny** [image-js/core#243]
What kind of names should we use for filter ? Currently we use short names like sobel, gaussian, blur, ...

However we have a problem with median. Median may be a filter and return an image that is based on the original image or it may a compute that will calculate the median of the pixels of each channels.

Should we systematically put sobelFilter, gaussianFilter, blurFilter, medianFilter, meanFilter, ... 

@targos What do you think ?

**Comment by targos** [comment]
I think it's not a bad idea to add the `Filter` suffix
