### ISSUE TITLE
Package name for npm

### ISSUE THREAD

**Issue by targos** [image-js/core#32]
We need to find a name to publish the package on npm.

It is not directly possible to use `ij`, as another ["project"](https://www.npmjs.com/package/ij) is squatting the name (this is not allowed, we could ask the npm team to delete it).

Anyway, IMHO `ij` is probably not the best name. Yes, it is short, but it's not easy to pronounce and it's not obvious what it means.

I think that whatever the name is, it should have the full "image" word in it.
So with that in mind, if we look in npm there are already:
* [image](https://www.npmjs.com/package/image): image format conversion
* [jimp](https://github.com/oliver-moran/jimp): basic image processing, only for node.
* [image-ninja](https://www.npmjs.com/package/image-ninja): same with less functionality
* [imagejs](https://www.npmjs.com/package/imagejs): same

`image-js` is still available. It is a bit redundant to add `js` because npm packages are by definition written in JavaScript, but unless we find something else, it is a good option that reflects the name of the organisation and the domain name(s).

**Comment by lpatiny** [comment]
I think we should go for image-js

It is like that the same name as the website

**Comment by targos** [comment]
OK, if there is no objection from @image-js/collaborators I will publish it under the name image-js tomorrow

**Comment by targos** [comment]
https://www.npmjs.com/package/image-js
