### ISSUE TITLE
extending method with property : allow parameters

### ISSUE THREAD

**Issue by lpatiny** [image-js/core#61]
Image.extendMethod('getPixelsArray', getPixelsArray);

I would like to extend a Image with property that call function with parameters like:

Image.extendProperty('transparent', getPixelsArray, {alpha: 0});
Image.extendProperty('opaque', getPixelsArray, {alpha: 255});

**Comment by targos** [comment]
You can have partial application for both `extendMethod` and `extendProperty`.

Example:

```js
Image.extendProperty('opaque', getPixelsArray, {partialArgs: [{alpha: 255}]})
```
