### ISSUE TITLE
Should we make a big refactoring ?

### ISSUE THREAD

**Issue by lpatiny** [image-js/core#79]
Should the data be saved in another format ?
Current proposal :
* array (components) of array (points)
* array (components) of matrix (points)
* array (stack of image) of array (components) of matrix (points)
I would prefer the last solution if there is no impact on speed

**Comment by lpatiny** [comment]
Array versus Matrix versus Encapsulated Matrix
http://jsperf.com/lp-matrix-versus-array/2

**Comment by lpatiny** [comment]
Inverting the pixels
http://jsperf.com/lp-invert/8
Check matrix versus matrix-inverted. The order really matters !!!!!
On the other hand a matrix of uint8 is the same as an array of uint8 !

**Comment by lpatiny** [comment]
On a side node we have compare the syntax of a for 'of' to a normal for loop and the difference seems huge !
for of should probably not be used. @targos do you see an error in this test case ?
http://jsperf.com/lp-for-of/2

**Comment by lpatiny** [comment]
What I would suggest is to forget about set of images. Should be another class that is called "stack"
That the images are stored as an array (component) of matrix.

**Comment by targos** [comment]
I'm quite sure we cannot use jsperf here. There are too many things involved in image objects

**Comment by targos** [comment]
Copy from UintArray of RGBARGBA... http://jsperf.com/load-image-into-array-or-matrix/2

**Comment by targos** [comment]
Crop on 1D array vs matrix: http://jsperf.com/crop-image-from-array-or-matrix/2

**Comment by targos** [comment]
It was decided to hold on for now because we are not sure that it is a complete win.
In case we need to do it, we will probably use the `array (components) of typed arrays (points)` approach.
The new benchmark in https://github.com/image-js/core/blob/377f0c20890d284fbf5a80568d1ac74a840adc8c/benchmark/dataFormat.js can help making the decision.

**Comment by targos** [comment]
example of code that is not happy with this approach:
http://jsperf.com/access-array-elements-grouped/2

**Comment by lpatiny** [comment]
while I can not reach the single array performance there is a way to improve the code a little bit
http://jsperf.com/access-array-elements-grouped/5
(I had to reduce the size of the array to have reliable results)
