### ISSUE TITLE
Investigate failing test in test/node/operator/extract.js

### ISSUE THREAD

**Issue by targos** [image-js/core#80]
For some reason, this test is only failing on Travis
Example of failure: https://travis-ci.org/image-js/core/jobs/81538437

**Comment by lpatiny** [comment]
The mask was not giving my expected result. I changed it and it pass again locally. Waiting for Travais ...

**Comment by targos** [comment]
I skipped the test, you need to re-enable it to test on Travis

**Comment by lpatiny** [comment]
Seems it fails with node v4.1 and pass with node v4.0. I can succeed to reproduce the bug locally. It is clearly random !
It looks like it is related to the creation of the Uint8array of size 1. Still investigating
